<FORM method=GET 
action=http://www.google.com/custom target=_blank>
	<TABLE bgcolor=#FFFFFF 
cellspacing=0 border=0 cellpadding="0">
<TR><TD><IMG SRC="images/websearchtop.gif"></TD></TR>
 <tr valign=top><td> 
	<table width="400" cellspacing="0" cellpadding="0" id="table1" style="border: 2px solid #2857AA">
		<tr>
			<td height="50"> 
			<p align="left">&nbsp;&nbsp;&nbsp; 
			<INPUT TYPE=text name=q size=26 maxlength=255 value="">&nbsp;&nbsp; 
			<INPUT type=submit name=sa VALUE="Web Search">
			</td>
		</tr>
		<tr>
			<td background="images/framebottom.gif"> 
			&nbsp;</td>
		</tr>
	</table>
&nbsp;<INPUT type=hidden name=cof VALUE="AH:center;S:http://www.richtemplate.com;AWFID:a87117e88b14af31;"></td></tr></TABLE> </FORM> 
