<table border="0" width="780" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%" BACKGROUND="images/yellowline.gif" bgcolor="#ffffff" valign="top">&nbsp;</td></tr>
    </table>
<table border="0" width="780" cellspacing="0" cellpadding="0" bgcolor="#940018" height="3">
  <tr>
    <td width="100%" bgcolor="#003163">
      <p align="center"><font color="#FFFFFF" face="Verdana" size="1">© DC
      RichTemplates, Inc. - (571) 455-9021 </font></td>
  </tr>
</table>