<table border="0" bgcolor="#639A9C" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%" background="images/bannerback4.gif"><img border="0" src="images/banner3.gif"></td>
  </tr>
</table>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="531" bgcolor="#ffffff" height="30"valign="top"><img border="0" src="images/yellowline.gif"><br>
      <font size="1" face="Verdana">Welcome to RichPortal Today is&nbsp;<%=date%> and EDT
      is <%=time%>.</font></td>
    <td width="100%" height="30" valign="top" background="images/yellowlineback.gif">
     <img border="0" src="images/RichPortal2.gif" width="219" height="30" align="right">
    </td>
  </tr>
  </table>
  <table
    <tr>
    <td width="750" valign="top" colspan="2" class="mainHeaderTable"><font face="Verdana" size="2"><a href="newsletter.asp">Home</a>
      <font color="#FFFFFF">|</font> <a href="directory.asp">Employee Directory</a>
      <font color="#FFFFFF">|</font> <a href="compdocs.asp">Documents</a> <font color="#FFFFFF">|</font>
      <a href="articles.asp">Articles &amp; Resources</a> <font color="#FFFFFF">|
      <a href="vendors.asp">Vendor Contacts</a></font>&nbsp; <font color="#FFFFFF">|
      </font>Admin</font></td>
  </tr>
</table>