<%if Session("sectionid")="10" then
%>


<img src="data/images/realestate_subbanner.gif">

<%

elseif Session("sectionid")="7" then

%>
<img src="data/images/lodging_subbanner.gif">


<%


elseif Session("sectionid")="1" then

%>
<img src="data/images/golf_subbanner.gif">

<%


elseif Session("sectionid")="11" then

%>
<img src="data/images/timeshare_subbanner.gif">

<%


elseif Session("sectionid")="9" then

%>
<img src="data/images/restaurant_subbanner.gif">

<%


elseif Session("sectionid")="15" then

%>
<img src="data/images/retail_subbanner.gif">

<%


elseif Session("sectionid")="8" then

%>
<img src="data/images/vacation_subbanner.gif">

<%


elseif Session("sectionid")="13" then

%>
<img src="data/images/mfghomes_subbanner.gif">

<%


elseif Session("sectionid")="14" then

%>
<img src="data/images/pinnacle_subbanner.gif">


<%


elseif Session("sectionid")="12" then

%>
<img src="data/images/building_subbanner.gif">

<%


elseif Session("sectionid")="16" then

%>
<img src="data/images/about_subbanner.gif">


<%end if%>