<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_global.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## Global Settings ##

'## editimage.asp, logs.asp, system.asp, upload.asp & users.asp
CONST IG_timeout 	= "Your login session will timeout in 2 minutes. To continue your current session, please navigate to a new page."

'## header.asp
CONST IGhead_homep 	= "i-Gallery Home Page"
CONST IGhead_lgoff 	= "Log Off"
CONST IGhead_lgon 	= "Log On"

'## menu.asp
CONST IGmenu_spo 	= "Submit Photo(s) Online"
CONST IGmenu_subfrm = "Submission Form"
CONST IGmenu_ua 	= "User Administration"
CONST IGmenu_mu 	= "Manage User(s)"
CONST IGmenu_ulf 	= "User(s) Log Files"
CONST IGmenu_smngt 	= "System Management"
CONST IGmenu_smaint = "System Maintenance"
CONST IGmenu_candr  = "Compact & Repair Database"
CONST IGmenu_mb  	= "MESSAGE BOARD"

'## searchform.asp
CONST IGsform_sg 	= "Search Gallery"
CONST IGsform_but 	= "GO"
CONST IGsform_xm 	= "Exact Match"

'## footer.asp
CONST IGfoot_his1 	= "Within 7 Days"
CONST IGfoot_his2 	= "14 Days"
CONST IGfoot_his3 	= "21 Days"
CONST IGfoot_pb 	= "Powered By"
%>

