<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_syncimage.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## syncimage.asp
CONST IGsync_msg 	= "The file has been added to the i-Gallery database. It is now a searchable item!"
CONST IGsync_link1 	= "Edit Profile"
CONST IGsync_link2 	= "Close Window"
%>