<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_logs.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## logs.asp
CONST IGlgs_alrt1 	= "Are you sure you want to permanently delete the selected \""Log(s)\"" from the i-Gallery database?  All information will be lost!"
CONST IGlgs_alrt2 	= "Are you sure you want to permanently delete the selected \""Log\"" from the i-Gallery database?  All information will be lost!"
CONST IGlgs_deltitl = "User Log(s) Deleted"
CONST IGlgs_delmsgl = "The individual ""User Log"" you selected has been successfully deleted from the database.&nbsp; <a class=""link"" href=""logs.asp"">Click Here</a> to return to the ""User Access Log"" page or you will be redirected automatically in 5 seconds."
CONST IGlgs_delmsg2 = "The ""User Logs"" you selected have been successfully deleted from the database.&nbsp; <a class=""link"" href=""logs.asp"">Click Here</a> to return to the ""User Access Log"" page or you will be redirected automatically in 5 seconds."
CONST IGlgs_titl 	= "User Access Log(s)"
CONST IGlgs_msgl 	= "Listed below are the current ""User Access Logs"" on file.&nbsp; To delete a user log from the database click on the ""X"" next to the entry."
CONST IGlgs_msg2 	= "There are currently no user logs on file!"
CONST IGlgs_grd1 	= "Name"
CONST IGlgs_grd2 	= "Email Address"
CONST IGlgs_grd3 	= "Last Date In"
CONST IGlgs_grd4 	= "Logs"
CONST IGlgs_but 	= "Delete Selected Log(s)"
CONST IGlgs_page1 	= "Records Per Page - Displaying Page"
CONST IGlgs_page2 	= "of"
%>