<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_users.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## users.asp
CONST IGusr_add 		= "Add New Administrator"
CONST IGusr_addmsg 		= "Fill out the form below to add a new administrator to the i-Gallery administrative database.&nbsp; Please Note: All fields are required when adding an administrator profile."
CONST IGusr_form1 		= "First Name"
CONST IGusr_form2 		= "Last Name"
CONST IGusr_form3 		= "Email Address"
CONST IGusr_form4 		= "Username"
CONST IGusr_form5 		= "Password"
CONST IGusr_form6a 		= "Privilege"
CONST IGusr_form6b 		= "Select Access Level"
CONST IGusr_form6c 		= "View and Edit"
CONST IGusr_form6d 		= "Full Site Administrator"
CONST IGusr_but1 		= "Add New Administrator"
CONST IGusr_but2 		= "Edit User Profile"
CONST IGusr_err1 		= "The <b>""First Name""</b> field is required!"
CONST IGusr_err2 		= "The <b>""Last Name""</b> field is required!"
CONST IGusr_err3 		= "The <b>""Email Address""</b> field contains an invalid email address."
CONST IGusr_err4 		= "The <b>""User Name""</b> field is required!"
CONST IGusr_err5 		= "The <b>""Password""</b> field is required!"
CONST IGusr_err6 		= "The <b>""User Level""</b> field is required!"
CONST IGusr_err 		= "Error!"
CONST IGusr_errmsg 		= "There has been an error processing your request!&nbsp; <b>Please Note:</b>  All fields are required when submitting this form."
CONST IGusr_folw 		= "Please review the following fields!"
CONST IGusr_click 		= "Click here to correct the problem."
CONST IGusr_addsuc 		= "New Administrator Added"
CONST IGusr_addsucmsg 	= "The administrator profile has been successfully added to the database.&nbsp; <a class=""linkmed"" href=""users.asp"">Click Here</a> to return to the ""Administrator(s)"" profile page or you will be redirected automatically in 5 seconds."
CONST IGusr_upd 		= "Update Administrator Profile"
CONST IGusr_updmsg 		= "<b>Please Note:</b>  All fields are required when updating a administrators profile.&nbsp; To delete a profile return to the previous screen and click the ""X"" button next to the profile you want to delete.&nbsp; <a class=""linkmed"" href=""javascript: history.back(-1);"">Click Here</a> to return to the previous page."
CONST IGusr_updsuc 		= "Update Administrator Profile"
CONST IGusr_updsucmsg 	= "The administrator profile has been successfully updated.&nbsp; <a class=""linkmed"" href=""users.asp"">Click Here</a> to return to the ""Administrators"" profile page or you will be redirected automatically in 5 seconds."
CONST IGusr_warn 		= "Are you sure you want to permanently delete the selected \""User\"" from the i-Gallery database?  All information will be lost!"
CONST IGusr_del 		= "Delete Administrator Profile"
CONST IGusr_delmsg 		= "The administrator you selected has been successfully deleted from the database.&nbsp; <a class=""link"" href=""users.asp"">Click Here</a> to return to the ""Administrators"" profile page or you will be redirected automatically in 5 seconds."
CONST IGusr_mng 		= "Manage Current Administrators"
CONST IGusr_mngmsg 		= "To edit an administrator profile click on the pencil.&nbsp; To delete an administrator click on the ""X"" next to the administrator you want to delete."
CONST IGusr_mngg1 		= "Last Name, First Name"
CONST IGusr_mngg2 		= "Email Address"
CONST IGusr_mngg3 		= "Added"
CONST IGusr_mngg4 		= "Edit Admin."
CONST IGusr_mngg5 		= "Delete Admin."
CONST IGusr_page 		= "Records Per Page - Displaying Page"
%>