<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_login.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## login.asp
CONST IGlog_both 	= "The User Name and Password fields are empty!"
CONST IGlog_name 	= "The Username field was left empty!"
CONST IGlog_pass 	= "The Password field was left empty!"
CONST IGlog_nof 	= "Sign In Information is not on file!"
CONST IGlog_na 		= "Authorization Required!"
CONST IGlog_auth 	= "Authentication Required!"
CONST IGlog_usern 	= "User Name"
CONST IGlog_passw 	= "Password"
CONST IGlog_rem 	= "Remember Me"
CONST IGlog_but1 	= "Sign In"
%>