<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_igallery.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## igallery.asp
CONST IG_uol 			= "Up One level"
CONST IG_pg1 			= "Displaying Page"
CONST IG_pg2 			= "of"
CONST IG_erfm1 			= "Use the ""Create New Folder"" form below to add your first sub-directory to your main i-Gallery folder."
CONST IG_erfm2 			= "There are currently no folders within your main folder.&nbsp; To create a new directory you must first log-in to the system administration section.&nbsp; <a class=""link"" href=""login.asp"">Click Here</a> to log-in now."
CONST IG_ded 			= "DO YOU WANT TO DELETE THIS EMPTY FOLDER"
CONST IG_ri 			= "Repair Broken Thumbnails In This Folder"
CONST IG_si 			= "Sync All Images In This Folder To Database"
CONST IG_cnd1 			= "Create New Directory"
CONST IG_cnd2 			= "Create New Sub-Directory"
CONST IG_rnd1 			= "Re-Name This Directory"
CONST IG_edm 			= "There are currently no images to view within this directory."
CONST IG_upttf1 		= "Upload Pictures To This Folder"
CONST IG_upttf2 		= "Main Folder"
CONST IG_but1 			= "Create"
CONST IG_but2 			= "Re-Name"

'## toolbar.asp
CONST IGt_editimage 	= "Edit Image"
CONST IGt_viewimage 	= "View Image"
CONST IGt_rotateimagel 	= "Rotate Image 90&ordm; Left"
CONST IGt_centerimage 	= "Center Image"
CONST IGt_rotateimager 	= "Rotate Image 90&ordm; Right"
CONST IGt_dwnimage 		= "Download Image"

'## igallery.inc
CONST IGi_add 			= "Added"
CONST IGi_ht 			= "Height"
CONST IGi_wd 			= "Width"
CONST IGi_un 			= "Unknown"
CONST IGi_mod 			= "Mod."
CONST IGi_sz 			= "Size"
CONST IGi_adjprop 		= "Edit Properties"
CONST IGi_view 			= "Click Here To View"
CONST IGi_vote 			= "Click Here To Vote"
CONST IGi_tv 			= "Total Vote(s)"
CONST IGi_views 		= "Views"
CONST IGi_dwnaudio 		= "Download Audio File"
CONST IGi_editaudio 	= "Edit Audio File"
CONST IGi_dwnvideo 		= "Download Video File"
CONST IGi_editvideo 	= "Edit Video File"
CONST IGi_dwnld 		= "Download"
CONST IGi_dwnlds 		= "Downloads"
CONST IGi_f 			= "File"
CONST IGi_desc 			= "Description"
CONST IGi_unkn 			= "Unknown"
CONST IGi_delunkn 		= "Delete Unknown File"
%>

