<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_editimage.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## editimage.asp
CONST IGei_click 	= "Click Here To Rename File"
CONST IGei_rtnfldr 	= "Return To Folder"
CONST IGei_adj1 	= "Adjust Size & Rotation"
CONST IGei_adj2 	= "Adjust Image Size"
CONST IGei_img1 	= "Click To View"
CONST IGei_img2 	= "Viewer"
CONST IGei_dwnaudio = "Download Audio File"
CONST IGei_dwnvideo = "Download Video File"
CONST IGei_f 		= "File"
CONST IGei_unkn 	= "Unknown"
CONST IGei_title 	= "Photo Title"
CONST IGei_desc 	= "Photo Description"
CONST IGei_max 		= "Max"
CONST IGei_maxchar 	= "Max Char"
CONST IGei_move1 	= "Move This File To"
CONST IGei_move2 	= "Move To Folder"
CONST IGei_copy1 	= "Copy This File To"
CONST IGei_copy2 	= "Copy To Folder"
CONST IGei_del1 	= "Delete File From This Folder!"
CONST IGei_del2 	= "Confirm"
CONST IGei_msg1 	= "Image Details Saved Successfully!"
CONST IGei_msg2 	= "Image Renamed Successfully!"
CONST IGei_but1 	= "Rename"
CONST IGei_but2 	= "Update"
CONST IGei_but3 	= "Move"
CONST IGei_but4 	= "Copy"
CONST IGei_but5 	= "Delete Image"
%>