<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_photoproperties.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## photoproperties.asp
CONST IGpp_adj1 	= "Note"
CONST IGpp_adj2 	= "The image has been sized from"
CONST IGpp_adj3 	= "pixels to"
CONST IGpp_adj4 	= "pixels"
CONST IGpp_shrp1 	= "The image has been sharpened and rotated 90&deg;"
CONST IGpp_shrp2 	= "CCW" ' Counter Clockwise
CONST IGpp_shrp3 	= "CW"  ' Clockwise
CONST IGpp_shrp4 	= "The image has been sharpened."
CONST IGpp_opmsg1 	= "The dimension of this image are currently set at"
CONST IGpp_opmsg2 	= "pixels"
CONST IGpp_opmsg3 	= "To support most monitor settings we recommend you resize this image to a <b>width</b> no larger then 800 pixels and a <b>height</b> no larger then 600 pixels."
CONST IGpp_opmsg4 	= "This image is sized appropriately for most monitors."
CONST IGpp_fldset1 	= "Resize Image"
CONST IGpp_frm1 	= "Scale Image @"
CONST IGpp_frm1a 	= "Choose Percent"
CONST IGpp_frm1b 	= "pixels"
CONST IGpp_frm2 	= "New Width"
CONST IGpp_frm2a 	= "Pixels"
CONST IGpp_frm3 	= "New Height"
CONST IGpp_frm3a 	= "Pixels"
CONST IGpp_frm4 	= "Sharpen Image"
CONST IGpp_frm4a 	= "(must be > 100)"
CONST IGpp_frm5 	= "Rotate Image"
CONST IGpp_frm5a 	= "90&deg; Left"
CONST IGpp_frm5b 	= "90&deg; Right"
CONST IGpp_frm5c 	= "No Rotation"
CONST IGpp_cursize 	= "Current Size"
CONST IGpp_viewfi 	= "View Full Image"
CONST IGpp_but 		= "Apply Changes"
%>