<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_vote.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## vote.asp
CONST IGvote_err 		= "Error!"
CONST IGvote_errmsg 	= "The file you have attempted to vote for does not exisit.&nbsp; If you feel you have reached this message in error please contact the"
CONST IGvote_sysadm 	= "system administrator"
CONST IGvote_close 		= "Close This Window"
CONST IGvote_suc 		= "Vote Recorded!"
CONST IGvote_sucmsg 	= "Your vote has been successfully recorded.&nbsp; Thank you for taking the time to give us your opinion on this item.&nbsp; Have a great day!"
CONST IGvote_perr 		= "Processing Error!"
CONST IGvote_perrmsg 	= "According to the information we have on file you have already voted for this item.  If you feel you have reached this message in error please contact the"
CONST IGvote_vb 		= "Voting Booth"
CONST IGvote_af 		= "Audio File"
CONST IGvote_vf 		= "Video File"
CONST IGvote_but 		= "Cast Your Vote!"
%>