<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_sendtofriend.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## sendtofriend.asp
CONST IGstf_alrt1 	= "Please enter a value in the \""Your Name\"" field!"
CONST IGstf_alrt2 	= "The \""Your Email\"" field contains an invalid email address or the field was left blank."
CONST IGstf_alrt3 	= "Please enter a value in the \""Their Name\"" field!"
CONST IGstf_alrt4 	= "The \""Their Email\"" field contains an invalid email address or the field was left blank."
CONST IGstf_emsg1 	= "i-Gallery - Email Photo"
CONST IGstf_emsg2 	= "The following image has been forwarded to you at the request of"
CONST IGstf_emsg3 	= "Personal Message"
CONST IGstf_emsg4 	= "Have A Great Day!"
CONST IGstf_head1 	= "Message Sent Successfully!"
CONST IGstf_sucs1 	= "Greetings"
CONST IGstf_sucs2 	= "The image you selected has been successfully delivered to"
CONST IGstf_sucs3 	= "<a class=""link"" href=""igallery.asp"">Click Here</a> to return to the main i-Gallery folder."
CONST IGstf_fail1 	= "The ""Send To A Friend"" form was <b>not</b> sent successfully.&nbsp; We could be experiencing temporary server problems.&nbsp; Please try again at a later time."
CONST IGstf_fail2 	= "Error"
CONST IGstf_head2 	= "Email This Photo"
CONST IGstf_etptxt 	= "Here is the image you are requesting to email to your friend or colleague.&nbsp; Fill in the form below with the addressing information requested and we will send your image off.&nbsp; Please note all fields are required."
CONST IGstf_frm1 	= "Your Name"
CONST IGstf_frm2 	= "Your Email"
CONST IGstf_frm3 	= "Their Name"
CONST IGstf_frm4 	= "Their Email"
CONST IGstf_frm5 	= "I found this image on the Web and I thought you might enjoy it also!"
CONST IGstf_but1 	= "Send Photo"
%>