<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_viewphoto.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## viewphoto.asp
CONST IGvp_dimg 	= "Download Image"
CONST IGvp_eimg 	= "Email Image"
CONST IGvp_pimg 	= "Print Image"
CONST IGvp_rsmenu 	= "Resize Image Menu"
CONST IGvp_aemenu 	= "Artistic Effects Menu"
CONST IGvp_close 	= "Close Image Viewer"
CONST IGvp_audio 	= "Audio File"
CONST IGvp_dwnaudio = "Download Audio File"
CONST IGvp_video 	= "Video File"
CONST IGvp_dwnvideo = "Download Video File"
CONST IGvp_unknwn 	= "Unknown"
CONST IGvp_f 		= "Unknown"
CONST IGvp_pi 		= "Previous Image"
CONST IGvp_start 	= "Start Slideshow"
CONST IGvp_stop 	= "Stop Slideshow"
CONST IGvp_ni 		= "Next Image"
CONST IGvp_rszmsg 	= "This image has been resized to fit your screen.&nbsp; <u>Click Here</u> to resize this image to it's original size."
CONST IGvp_p1 		= "Print Screen"
CONST IGvp_p2 		= "Printer Friendly"
CONST IGvp_zoom1 	= "Zoom Out 25%"
CONST IGvp_zoom2 	= "Zoom Out 50%"
CONST IGvp_zoom3 	= "Zoom Out 75%"
CONST IGvp_zoom4 	= "Zoom In 25%"
CONST IGvp_zoom5 	= "Zoom In 50%"
CONST IGvp_zoom6 	= "Zoom In 75%"
CONST IGvp_zoom7 	= "Zoom In 100%"
CONST IGvp_zoom8 	= "Fit To Screen"
CONST IGvp_zoom9 	= "Revert To Original Size"
CONST IGvp_eff1 	= "Blur"
CONST IGvp_eff2 	= "Emboss"
CONST IGvp_eff3 	= "Engrave"
CONST IGvp_eff4 	= "Grayscale"
CONST IGvp_eff5 	= "Invert"
CONST IGvp_eff6 	= "Mirror"
CONST IGvp_eff7 	= "Pixelate"
CONST IGvp_eff8 	= "Rotate - 180&ordm;"
CONST IGvp_eff9 	= "X-Ray"
CONST IGvp_eff10 	= "Revert"
%>