<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_search.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## search.asp
CONST IGsrch_sr 		= "Search Results"
CONST IGsrch_pg 		= "Page"
CONST IGsrch_null1 		= "Your search for"
CONST IGsrch_null2 		= "yielded no results!&nbsp; Please narrow your search criteria and try again"
CONST IGsrch_null3 		= "The search field was left empty!"

'## searchresults.asp
CONST IGsrslt_nm 		= "Name"
CONST IGsrslt_indx  	= "Indexed"
CONST IGsrslt_title 	= "Title"
CONST IGsrslt_desc 		= "Description"
CONST IGsrslt_ctvi 		= "Click To View Image"
CONST IGsrslt_dwnaudio 	= "Download Audio File"
CONST IGsrslt_dwnvideo 	= "Download Video File"
CONST IGsrslt_dir 		= "Directory"
CONST IGsrslt_eimg 		= "Edit Image"
CONST IGsrslt_vimg 		= "View Image"
CONST IGsrslt_dimg 		= "Download Image"
CONST IGsrslt_cte 		= "Click To Enlarge"
CONST IGsrslt_edtaudio 	= "Edit Audio File"
CONST IGsrslt_edtvideo 	= "Edit Video File"
CONST IGsrslt_dwn 		= "Download"
CONST IGsrslt_f 		= "File"
%>